name: two_zero_four_eight
description: A new Flutter project.

environment:
  sdk: '>=2.17.0 <4.0.0' # Adjust the version range as needed

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.13
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  image_path_android: "assets/icon.png"
  image_path_ios: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - icon.png

  fonts:
    - family: StarJedi
      fonts:
        - asset: fonts/starjedi.ttf
